"""Project file management for web-dossier harness."""

from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any

from cli_anything.web_dossier.core.pipeline import default_pipelines


REQUIRED_MARKERS = [
    "README.md",
    "production",
    "tests/integration/package.json",
]


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def validate_source_path(source_path: str) -> dict[str, Any]:
    path = Path(source_path).resolve()
    result = {
        "source_path": str(path),
        "exists": path.exists(),
        "is_dir": path.is_dir(),
        "missing_markers": [],
        "valid": False,
    }
    if not path.exists() or not path.is_dir():
        return result

    for marker in REQUIRED_MARKERS:
        if not (path / marker).exists():
            result["missing_markers"].append(marker)

    result["valid"] = len(result["missing_markers"]) == 0
    return result


def create_project(source_path: str, name: str = "web-dossier") -> dict[str, Any]:
    return {
        "version": "1.0",
        "name": name,
        "source_path": str(Path(source_path).resolve()),
        "created_at": now_iso(),
        "updated_at": now_iso(),
        "pipelines": default_pipelines(),
        "notes": "Generated by cli-anything-web-dossier",
    }


def save_project(project: dict[str, Any], output_path: str) -> str:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    project["updated_at"] = now_iso()
    path.write_text(json.dumps(project, indent=2), encoding="utf-8")
    return str(path)


def load_project(project_path: str) -> dict[str, Any]:
    path = Path(project_path)
    return json.loads(path.read_text(encoding="utf-8"))


def project_info(project: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": project.get("name"),
        "source_path": project.get("source_path"),
        "pipeline_count": len(project.get("pipelines", {})),
        "created_at": project.get("created_at"),
        "updated_at": project.get("updated_at"),
    }
